apply plugin: 'maven-publish'
apply plugin: 'signing'
apply from: "${rootDir}/gradle/artifact-settings.gradle"
apply from: "${rootDir}/gradle/publish-root.gradle"

task androidJavadocs(type: Javadoc) {
    source = android.sourceSets.main.java.sourceFiles
    classpath = files(android.bootClasspath)
    failOnError = false
}

task androidJavadocsJar(type: Jar, dependsOn: androidJavadocs) {
    archiveClassifier = 'javadoc'
    from androidJavadocs.destinationDir
}

task androidSourcesJar(type: Jar) {
    archiveClassifier = 'sources'
    from android.sourceSets.main.java.srcDirs
    from android.sourceSets.main.kotlin.srcDirs
}

tasks.withType(Javadoc) {
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('docencoding', 'UTF-8')
    options.addStringOption('charset', 'UTF-8')
}

// artifacts {
//     archives androidSourcesJar
//     archives androidJavadocsJar
// }

logger.lifecycle(ext["versionName"])

version = project.ext.versionName
group = project.ext.mapvinaArtifactGroupId

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId this.group
                artifactId project.project.ext.mapvinaArtifactId
                version this.version

                from components.release

                artifact androidJavadocsJar

                pom {
                    name = project.ext.mapvinaArtifactTitle
                    description = project.ext.mapvinaArtifactTitle
                    url = project.ext.mapvinaArtifactUrl
                    licenses {
                        license {
                            name = project.ext.mapvinaArtifactLicenseName
                            url = project.ext.mapvinaArtifactLicenseUrl
                        }
                    }
                    developers {
                        developer {
                            id = project.ext.mapvinaDeveloperId
                            name = project.ext.mapvinaDeveloperName
                            email = 'mapvina@mapvina.com'
                        }
                    }
                    scm {
                        connection = project.ext.mapvinaArtifactScmUrl
                        developerConnection = project.ext.mapvinaArtifactScmUrl
                        url = project.ext.mapvinaArtifactUrl
                    }
                }
            }
        }
    }
}

afterEvaluate { project ->
    android.libraryVariants.all { variant ->
        tasks.androidJavadocs.doFirst {
            print("----------------------------------------------------------------------")
            classpath += files(variant.javaCompile.classpath.files)
        }
    }
}

signing {
    sign publishing.publications
}

tasks.withType(GenerateModuleMetadata) {
    dependsOn androidSourcesJar
    dependsOn androidJavadocsJar
}
